### ISSUE TITLE
Int list not working 

### ISSUE THREAD

**Issue by yellowthing0** [ZeynelKoca/LeagueOfLegends-int-list#2]
the int list intially worked after first launch but after that the int list always displays league client status offline, am unsure if I'm pathing the app correctly, tried reinstalling which didnt work.

**Comment by ZeynelKoca** [comment]
You need to set the path of the League of Legends folder itself, which is usually found on the location `C:\Riot Games\League of Legends`. You know that the directory path is correct if there's a file named `lockfile` in it when the client is running. 

Not exactly sure why it worked on the initial launch and no more after that. I don't think there's any functionality for storing the directory path if it was selected by hand, so you might have to set it again every time you start the application.

**Comment by yellowthing0** [comment]
Actually found out the real issue, it wasn't because of my pathing, it was because I changed my league of legends executable properties to allow multiple launchers to be open
