### ISSUE TITLE
My league folder is not the default one

### ISSUE THREAD

**Issue by adrmarty** [ZeynelKoca/LeagueOfLegends-int-list#3]
Would it be possible to save the league folder so that I dont have to select it every time? :D

**Comment by ZeynelKoca** [comment]
Added this feature in [v1.1.](https://github.com/ZeynelKoca/LeagueOfLegends-int-list/releases/tag/v1.1)

If you want to save your current int list, follow the setup file and open the new int list app at least once. After that, head on to your Roaming folder (`C:\Users\NAME\AppData\Roaming`) and move the `DbList.xml` into the subdirectory at `C:\Users\NAME\AppData\Roaming\IntList`.
There will be an empty `DbList.xml` file there, you can replace that with your old one.
