### ISSUE TITLE
Cannot launch app

### ISSUE THREAD

**Issue by BattleMouth23** [ZeynelKoca/LeagueOfLegends-int-list#7]
How do I launch app, tried to open but says set up isn't recognized on visual studio no idea how this works

**Comment by ZeynelKoca** [comment]
Not completely sure what your question is, but assuming you're on Windows and have the proper .NET runtimes installed: the entry point of the application is in `LoL_int_list > Program.cs`.

You can also install the app directly through one of the releases @ https://github.com/ZeynelKoca/LeagueOfLegends-int-list/releases

**Comment by BattleMouth23** [comment]
this worked thanks
